name: Release for Linux

on:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
  workflow_run:
    workflows: [Lint and test]
    types:
      - completed

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  release_linux:
    runs-on: ${{ matrix.os }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        if: ${{ startsWith(matrix.os, 'ubuntu') && startsWith(github.ref, 'refs/tags/v') }}
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Build native executable
        if: ${{ startsWith(matrix.os, 'ubuntu') && startsWith(github.ref, 'refs/tags/v') }}
        run: yarn install --network-timeout 1000000 && yarn package-linux
        env:
          GH_TOKEN: ${{ secrets.github_token }}

      - name: Release assets
        if: ${{ startsWith(matrix.os, 'ubuntu') && startsWith(github.ref, 'refs/tags/v') }}
        uses: ncipollo/release-action@v1
        with:
          draft: true
          allowUpdates: true
          artifacts: "bin/linux/*"
          token: ${{ secrets.GITHUB_TOKEN }}
